# Generated by Django 4.2.1 on 2023-05-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hajri', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='date_person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sabha', models.DateField()),
                ('ref_id', models.IntegerField()),
            ],
        ),
    ]
