# Generated by Django 4.2.1 on 2023-07-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='femail_person',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='family',
            name='male_person',
            field=models.SmallIntegerField(default=0),
        ),
    ]
