# Generated by Django 4.2.1 on 2023-07-09 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_family_femail_person_family_male_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family',
            old_name='femail_person',
            new_name='female_person',
        ),
        migrations.CreateModel(
            name='Sabha_attendance_entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_sabha', models.DateField(auto_now_add=True)),
                ('male_attended', models.SmallIntegerField(default=0)),
                ('female_attended', models.SmallIntegerField(default=0)),
                ('family_ref', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='attendance.family')),
            ],
        ),
    ]
